# **Assignment 3**

| **Name** |Pratham Sharma|
|-------- | ------ |
|**Roll No** | AC-1232 |
| **Batch** | 2023 |
| **Submitted to** | Prof. Sharanjit Kaur|

## **Question 1**

Create a dataframe having at least 3 columns and 50 rows to store numeric data generated using a randomfunction. Replace 10% of the values by null values whose index positions are generated using randomfunction.

Do the following:

1. Identify and count missing values in a dataframe.
2. Drop the column having more than 5 null values.
3. Identify the row label having maximum of the sum of all values in a row and drop that row.
4. Sort the dataframe on the basis of the first column.
5. Remove all duplicates from the first column.
6. Find the correlation between first and second column and covariance between second and thirdcolumn.
7. Detect the outliers and remove the rows having outliers.
8. Discretize second column and create 5 bins

In [3]:
import numpy as np
import pandas as pd

In [4]:
s=np.random.randint(1,100,size=(50,3))
s

array([[60, 74, 62],
       [66,  6, 30],
       [22, 43, 25],
       [32, 96,  6],
       [54, 92, 69],
       [49, 16, 44],
       [97, 95, 80],
       [94, 80, 28],
       [98,  5, 79],
       [26, 75, 95],
       [91, 67, 42],
       [95, 36, 29],
       [30, 77, 23],
       [57, 56, 56],
       [21,  6, 88],
       [37, 93,  8],
       [21,  6, 98],
       [67, 18, 32],
       [37, 63, 79],
       [80, 60, 40],
       [50, 87, 60],
       [ 6, 72, 72],
       [80, 25, 80],
       [69, 79, 70],
       [43,  2, 39],
       [ 2, 42, 31],
       [59, 90, 96],
       [55, 11, 60],
       [15, 10, 84],
       [99, 57, 53],
       [87, 98, 37],
       [47, 87, 37],
       [45, 20, 32],
       [83,  7, 51],
       [73, 49, 30],
       [ 6, 81, 35],
       [78, 11, 62],
       [42, 57, 73],
       [81, 67, 18],
       [ 9, 19,  5],
       [71, 64, 53],
       [55, 50, 11],
       [88, 87, 42],
       [23, 89, 20],
       [24, 70, 32],
       [ 9, 34, 43],
       [17, 68, 37],
       [47, 52,  5],
       [ 6,  9,  6],
       [11, 57, 75]])

In [6]:
df=pd.DataFrame(s,columns=["first","second","third"])
display(df)

    first  second  third
0      60      74     62
1      66       6     30
2      22      43     25
3      32      96      6
4      54      92     69
5      49      16     44
6      97      95     80
7      94      80     28
8      98       5     79
9      26      75     95
10     91      67     42
11     95      36     29
12     30      77     23
13     57      56     56
14     21       6     88
15     37      93      8
16     21       6     98
17     67      18     32
18     37      63     79
19     80      60     40
20     50      87     60
21      6      72     72
22     80      25     80
23     69      79     70
24     43       2     39
25      2      42     31
26     59      90     96
27     55      11     60
28     15      10     84
29     99      57     53
30     87      98     37
31     47      87     37
32     45      20     32
33     83       7     51
34     73      49     30
35      6      81     35
36     78      11     62
37     42      57     73
38     81      67     18
39      9      19      5
40     71      64     53
41     55      50     11
42     88      87     42
43     23      89     20
44     24      70     32
45      9      34     43
46     17      68     37
47     47      52      5
48      6       9      6
49     11      57     75

In [9]:
df.mean(axis=1).mean()

49.93999999999999

In [10]:
df.count(axis=1)

0     3
1     3
2     3
3     3
4     3
5     3
6     3
7     3
8     3
9     3
10    3
11    3
12    3
13    3
14    3
15    3
16    3
17    3
18    3
19    3
20    3
21    3
22    3
23    3
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    3
44    3
45    3
46    3
47    3
48    3
49    3
dtype: int64

In [11]:
f=[lambda x:x+1 if (x>m) else 0]
df.apply(f)

      first   second    third
   <lambda> <lambda> <lambda>
0        61       75       63
1        67        0        0
2         0        0        0
3         0       97        0
4        55       93       70
5         0        0        0
6        98       96       81
7        95       81        0
8        99        0       80
9         0       76       96
10       92       68        0
11       96        0        0
12        0       78        0
13       58       57       57
14        0        0       89
15        0       94        0
16        0        0       99
17       68        0        0
18        0       64       80
19       81       61        0
20       51       88       61
21        0       73       73
22       81        0       81
23       70       80       71
24        0        0        0
25        0        0        0
26       60       91       97
27       56        0       61
28        0        0       85
29      100       58       54
30       88       99        0
31        0       88        0
32        0        0        0
33       84        0       52
34       74        0        0
35        0       82        0
36       79        0       63
37        0       58       74
38       82       68        0
39        0        0        0
40       72       65       54
41       56       51        0
42       89       88        0
43        0       90        0
44        0       71        0
45        0        0        0
46        0       69        0
47        0       53        0
48        0        0        0
49        0       58       76

In [12]:
random_indices=np.random.randint(0,len(df),size=(1,3))

In [ ]:
s=np.random.randint(1,100,size=(50,3))
df=pd.DataFrame(s,columns=["first","second","third"])
display(df)